- name: install packages
  apt:
    name:
    - zip
    - unzip
    state: latest
    update_cache: true

- name: create ohdsi dir
  file:
    dest: "/home/{{ user_name }}/ohdsi"
    state: directory

- name: extract synpuf1k file
  unarchive:
    src: http://www.ltscomputingllc.com/wp-content/uploads/2018/08/synpuf1k_omop_cdm_5.2.2.zip
    dest: "/home/{{ user_name }}/ohdsi"
    remote_src: yes
    creates: "/home/{{ user_name }}/ohdsi/README.md"

- name: copy sql scripts to remote
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user_name }}/ohdsi/sql/"
  with_fileglob:
  - "{{ role_path }}/files/*.sql"

- name: clone cdm repo
  git:
    repo: https://github.com/OHDSI/CommonDataModel.git
    dest: "/home/{{ user_name }}/ohdsi/common_data_model"
    version: v5.2.2

- name: find files sql files in cdm repo
  find:
    paths: "/home/{{ user_name }}/ohdsi/common_data_model/PostgreSQL/"
    patterns: "*.sql"
    recurse: yes
  register: files_matched_subdirectory

- name: copy cdm sql to shared repo
  copy:
    src: "{{ item.path }}"
    dest: "/home/{{ user_name }}/ohdsi/sql/"
    remote_src: yes
  with_items:
  - "{{ files_matched_subdirectory.files }}"

## TODO these are not idempotent right now. rerunning causes issues
- name: create synpuf schema
  command: psql ohdsi -c "CREATE SCHEMA IF NOT EXISTS synpuf1k;"
  become: true
  become_user: postgres

- name: OMOP DDL
  command: psql ohdsi -f "/home/{{user_name}}/ohdsi/sql/OMOP CDM ddl - PostgreSQL.sql"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: --search_path=synpuf1k

- name: load data
  command: psql ohdsi -f "/home/{{user_name}}/ohdsi/sql/load_data.sql"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: --search_path=synpuf1k

- name: OMOP CDM constraints
  command: psql ohdsi -f "/home/{{user_name}}/ohdsi/sql/OMOP CDM constraints - PostgreSQL.sql"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: --search_path=synpuf1k

- name: OMOP CDM indexes
  command: psql ohdsi -f "/home/{{user_name}}/ohdsi/sql/OMOP CDM indexes required - PostgreSQL.sql"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: --search_path=synpuf1k

- name: Link tables to data
  command: psql ohdsi -f "/home/{{user_name}}/ohdsi/sql/link_api.sql"
  become: true
  become_user: postgres
  environment:
    PGOPTIONS: --search_path=synpuf5pct
