---

- name: install packages
  apt:
    name:
    - zip
    - unzip
    state: latest
    update_cache: true

- name: Download latest atlas release
  unarchive:
    src: https://github.com/OHDSI/Atlas/archive/released.zip
    dest: "{{ download_dir }}"
    remote_src: yes

- name: deploy app
  synchronize:
    src: "{{ download_dir }}/Atlas-released/"
    dest: /var/lib/tomcat8/webapps/atlas/
  delegate_to: "{{ inventory_hostname }}"

- name: copy local config
  copy:
    src: "{{ role_path }}/files/config-local.js"
    dest: /var/lib/tomcat8/webapps/atlas/js/
  notify:
      - restart tomcat
      - wait for tomcat to come back up
      - verify WebAPI is back up
