# TODO for development only so can connect to db remotely
- name: allow remote connections
  copy:
    src: "{{ role_path }}/files/pb_hba.conf"
    dest: /etc/postgresql/11/main/pg_hba.conf

- name: listen on all ports
  copy:
      src: "{{ role_path }}/files/postgresql.conf"
      dest: /etc/postgresql/11/main/postgresql.conf

- name: change postgres password
  postgresql_user:
    name: postgres
    password: postgres
  become: yes
  become_user: postgres

- name: restart postgresql
  service: name=postgresql state=restarted
