---

language: python
python: "3.6"
dist: xenial
sudo: true

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

## TODO 3 of alter default privileges using postgresql_privs module always report
## TODO changes. Leave for now.

script:
  - ansible-playbook -i provisioning/tests/inventory configure.yml --syntax-check
#  - ansible-playbook -i provisioning/tests/inventory configure.yml --connection=local --become
#  - >
#  ansible-playbook -i provisioning/tests/inventory configure.yml --connection=local --become
#  | grep -q 'changed=3.*failed=0'
#  && (echo 'Idempotence test: pass' && exit 0)
#  || (echo 'Idempotence test: fail' && exit 1)
