---
#TODO consolidate redundant tomcat handlers
#TODO figure out how to create nested roles (e.g. download data, postgres, etc)
#TODO simplify / cleanup directory structure in download / load data
#TODO maybe get the 1k from ftp://ftp.ohdsi.org/synpuf/ but slow
#TODO so probably need to run that task in parallel to rest
- name: Create Atlas stack
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - vars/main.yml

  roles:
  - postgres
  - postgres_remote_access
  - webapi
  - atlas
  - "download_{{ dataset }}"
  - load_data
  - achilles
