---
- name: Create Atlas stack
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - vars/main.yml

  roles:
  - createdb
  - postgres_remote_access
  - webapi
  - atlas
#  - load_synpuf5pct
  - load_synpuf1k
  - achilles
