---

- name: install packages
  apt:
    name:
    - zip
    - unzip
    state: latest
    update_cache: true

- name: create ohdsi dir
  file:
    dest: "{{ download_dir }}/{{ dataset }}"
    state: directory

- name: extract synpuf1k file
  unarchive:
    src: http://www.ltscomputingllc.com/wp-content/uploads/2018/08/synpuf1k_omop_cdm_5.2.2.zip
    dest: "{{ download_dir }}/{{ dataset }}"
    remote_src: yes
    creates: "{{ download_dir }}/{{ dataset }}/README.md"
