---
- name: allow remote connections
  copy:
    src: "{{ role_path }}/files/pb_hba.conf"
    dest: /etc/postgresql/11/main/pg_hba.conf
  notify: restart postgresql

- name: listen on all ports
  copy:
      src: "{{ role_path }}/files/postgresql.conf"
      dest: /etc/postgresql/11/main/postgresql.conf
  notify: restart postgresql

- name: change postgres password
  postgresql_user:
    name: postgres
    password: "{{ db_postgres_user_password }}"
  become: yes
  become_user: postgres

