---

- name: add an apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: add CRAN
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/

- name: Install R, and requirements
  apt:
    name:
      - r-base-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
      - default-jdk
    state: latest
    update_cache: true
  tags: packages

- name: configure rJava
  command: R CMD javareconf

- name: install r - packages
  copy:
    src: "{{ role_path }}/files/install_packages.R"
    dest: "{{ download_dir }}/install_packages.R"
    mode: a+x

- name: install r - packages
  command: >
    ./install_packages.R {{ item.name }} {{ item.type }} --no-save --no-restore-history
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  args:
    chdir: "{{ download_dir }}"
  with_items:
    - name: devtools
      type: package
    - name: OHDSI/OhdsiRTools
      type: github
    - name: OHDSI/Achilles
      type: github

- name: run achilles
  template:
     src: "{{role_path}}/files/run_achilles.j2"
     dest: "{{download_dir}}/run_achilles.R"
     mode: a+x

# TODO need to add a changed method so this doesn't always rerun
- name: run achilles
  command: "{{download_dir}}/run_achilles.R"
  notify:
    - restart tomcat
    - wait for tomcat to come back up
    - verify WebAPI is back up
