- name: add an apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: add CRAN
  apt_repository:
    repo: deb https://cloud.r-project.org/bin/linux/ubuntu xenial/

- name: Install R, and requirements
  apt:
    name:
      - r-base-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libxml2-dev
      - default-jdk
    state: latest
    update_cache: true
  tags: packages

- name: create results schema
  command: psql ohdsi -c "CREATE SCHEMA IF NOT EXISTS results;"
  become: true
  become_user: postgres

- name: change owner results schema
  command: psql ohdsi -c "ALTER SCHEMA results OWNER TO ohdsi_admin;"
  become: true
  become_user: postgres

- name: configure rJava
  command: R CMD javareconf

# from https://adamj.eu/tech/2014/07/19/installing-and-removing-r-packages-with-ansible/
# TODO move all of this into template
# https://github.com/OHDSI/Achilles/wiki/Additional-instructions-for-Linux
# https://github.com/Oefenweb/ansible-r/blob/master/templates/usr/local/bin/R-install-package.j2
# http://www.jason-french.com/blog/2013/03/11/installing-r-in-linux/
- name: install r - packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
  - devtools

- name: install r - devtools packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { devtools::install_github(c('{{ item }}')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - OHDSI/OhdsiRTools
    - OHDSI/Achilles

- name: run achilles
  script: "{{role_path}}/files/run_achilles.R"

- name: restart tomcat
  service: name=tomcat8 state=restarted


