---
- name: install packages
  apt:
    name:
    - zip
    - unzip
    state: latest
    update_cache: true

- name: clone ohdsi atlas
  git:
    repo: https://github.com/OHDSI/Atlas.git
    dest: "{{ www_download_dir }}/Atlas-released"
    version: v2.6.0

- name: deploy app
  synchronize:
    src: "{{ www_download_dir }}/Atlas-released/"
    dest: /var/lib/tomcat8/webapps/atlas/
    checksum: yes
    times: no
  delegate_to: "{{ inventory_hostname }}"

- name: copy local config
  template:
    src: "{{ role_path }}/files/config-local.j2"
    dest: /var/lib/tomcat8/webapps/atlas/js/config-local.js
  notify:
    - restart tomcat
    - verify WebAPI
